[tools]
golangci-lint = "2.7.0"
"go:gotest.tools/gotestsum" = "latest"
"vfox-pulumi:pulumi/pulumi-converter-terraform" = "latest"
"vfox-pulumi:pulumi/pulumi-aws" = "latest"
"vfox-pulumi:pulumi/pulumi-tls" = "latest"
